---

- name: jenkins-install | Add apt key
  action: apt_key url="{{ jenkins_apt_key }}"  state=present   
  
- name: jenkins-install | Add apt repo
  apt_repository: repo="{{ jenkins_apt_repository }}" update_cache=yes
  
- name: jenkins-install | Install jenkins
  apt: pkg={{item}}
  with_items: [curl, jenkins]
  
- name: jenkins-install | Install additional deb packages
  apt: pkg={{item}}
  with_items: jenkins_apt_packages

- name: jenkins-install | Setup passlib
  apt: pkg=python-passlib
  when: jenkins_proxy_auth

# vim:sw=2
