---

- name: jenkins-jobs | Manage jobs
  shell: java -jar {{jenkins_home}}/jenkins-cli.jar -s http://{{jenkins_http_host}}:{{jenkins_http_port}}{{ jenkins_prefix }}/ {{item.action}}-job {{item.name}}
  with_items: jenkins_jobs
