---

- name: jenkins restart
  service: name=jenkins state=restarted

- name: jenkins create jobs
  shell: java -jar {{jenkins_home}}/jenkins-cli.jar -s http://{{jenkins_http_host}}:{{jenkins_http_port}}/ {{item.action}}-job {{item.name}}
  with_items: jenkins_jobs

- name: nginx restart
  service: name=nginx state=restarted
  sudo: yes

- name: apache restart
  service: name=apache2 state=restarted
